### ISSUE TITLE
Impossible to use docker logs (at least when using journald)

### ISSUE THREAD

**Issue by 3v1n0** [docker-snap/docker-snap#16]
After some small modifications to home-assistant's supervised-installer (see https://github.com/home-assistant/supervised-installer/pull/140) I've been able to correctly install and use hassio in my raspberry pi4 running Ubuntu with docker-snap.
Once it's installed in a snap-readable prefix all works fine, but unfortunately it seems that logs are not properly readable via `docker logs homeassistant` (even though I can read them via journalctl):

```
Dec 29 00:57:33 uberry docker.dockerd[1760]: time="2020-12-29T00:57:33.891258733+01:00" level=error msg="Handler for GET /v1.40/containers/23984b41e39fbb180ce14baf502c5e86975216cde6ca0b481ddf863c4a05a63f/logs returned error: configured logging driver does not support reading"
```

To be clear, I've modified (before installing hassio) my `$(snap run --shell docker -c 'printenv SNAP_DATA')/config/daemon.json` to use:

```json
{
    "log-level":        "error",
    "storage-driver":   "overlay2",
    "log-driver":       "journald"
}
```

**Comment by tianon** [comment]
Nice catch!  I've opened https://github.com/docker-snap/docker-snap/pull/17 which should hopefully fix this (however, it might also require the `log-observe` interface to be defined and connected -- need to wait for the GitHub Actions to finish there to determine for sure because my local environment is always wonky/permissive about things like that).

**Comment by 3v1n0** [comment]
@tianon finally got time to test this again, works great!

Thanks
