### ISSUE TITLE
Mounting the host filesystem with --volume gives container full access to the device

### ISSUE THREAD

**Issue by mapero** [docker-snap/docker-snap#44]
Hi,

we run the docker snap on an ubuntu core device.
The snap is installed without privileged interface connected.
When running a docker container with the host filesystem (/) as volume, e.g. `-v /:/host`, the container has full access to the files of the host, including writing and deleting.

Our assumption was, that the docker snap is running in confined snap environment and should not be able to escape the confinement. It should only have access to the standard snap folders, e.g. $SNAP_DATA.

```
$ snap list
Name                    Version         Rev    Tracking       Publisher   Notes
core18                  20210611        2074   latest/stable  canonical✓  base
docker                  20.10.8         1125   -              canonical✓  -
pc                      18-2            104    18/stable      canonical✓  gadget
pc-kernel               4.15.0-147.151  788    18/stable      canonical✓  kernel
snapd                   2.51.1          12398  latest/stable  canonical✓  snapd
```

**Comment by anonymouse64** [comment]
Hi, thanks for filing this issue.

Unfortunately, dockerd is not able to fully operate under the sandbox that most normal strict snaps use due to it's varied implementation and the many bits of confinement that dockerd applies to it's docker containers. In order to operate at all, the docker snap has a specific interface from snapd, the `docker-support` interface which does it's best to confine dockerd, but cannot meaningfully prevent dockerd from being able to perform arbitrary sandbox escape due to all of the operations that need to be performed in order for dockerd to confine docker containers. This is evident from the description of the interface inside snapd:

https://github.com/snapcore/snapd/blob/cdf2a1577ac7b8f98b1201b0ae5fd8f3b3d10a52/interfaces/builtin/docker_support.go#L59-L63

The docker snap when used on an Ubuntu Core system relies on dockerd to confine it's docker containers, and operates under essentially the same threat model as docker packaged as a debian package; the main threat model is for containers breaking out of their confinement to elevate themselves to the level of confinement as dockerd. It is not really a feasible goal to confine dockerd to itself be limited such that if a container broke out and elevated its privileges to that of dockerd it would still be meaningfully confined and prevented from accessing the host unrestricted.

There are other projects which hope to do this sort of thing like "rootless mode", which actually now that I look at the documentation is no longer considered experimental: https://docs.docker.com/engine/security/rootless, but at the time the docker snap and docker-support interface inside snapd were initially developed this technology was not mature enough for us to rely on it for folks wanting to use the docker snap on Ubuntu Core. Perhaps that has changed now and a specific, new, and different snap like i.e. `rootless-docker` could be prototyped which does provide this kind of guarantee, but that would likely be a significant undertaking.

Thanks,
Ian

**Comment by mapero** [comment]
Thanks for the feedback.
So from my understanding that means it is by design but can be solved by creating a rootless docker snap. Correct?

It would be good if this information would be placed more prominent in the snaps description. It was not clear for us, that this is the case. Especially the "strict" mode and the "privileged" interface connotes that the daemon is actually running confined.

**Comment by anonymouse64** [comment]
> So from my understanding that means it is by design but can be solved by creating a rootless docker snap. Correct?

Correct.

> It would be good if this information would be placed more prominent in the snaps description

Sure, PR's to the snap's description are welcome or perhaps @tianon could think of a way to communicate this.

> connotes that the daemon is actually running confined

Well it is running _confined_, just not _meaningfully_ confined if dockerd decided to be malicious.
