### ISSUE TITLE
Cannot create symlink in "/etc/docker"

### ISSUE THREAD

**Issue by jkfran** [docker-snap/docker-snap#45]
The installation of the docker snap has an issue when the `/etc/docker` folder is not empty:

```
cannot perform the following tasks:
- Run install hook of "docker" snap if present (run hook "install": 
-----
cannot update snap namespace: cannot create symlink in "/etc/docker": existing file in the way
snap-update-ns failed with code 1
-----)
```

This issue is blocking our CI process, because GitHub Action machines can't install the snap because of this.

Would it be possible to switch from the symlink to a bind mount?

**Comment by tianon** [comment]
Gah, I switched it to a symlink in https://github.com/docker-snap/docker-snap/pull/27 because the docs claimed it was better (admittedly without any real receipts), but I didn't realize whether that worked was dependent on each host filesystem where it gets installed; that seems kind of useless. :disappointed: :confused:

Guess we'll need to switch it back to `bind`.
